### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by wagiro**
Hi,

I write some improvements:

1- You can specify IP or IP and domain, for multiples domains in shared hosting.

`fmt.Println("Usage: ", os.Args[0], "<ip> <port> <threads> <page> <get/post> <seconds> <header.txt/nil> <domain/nil>")`

2- When target is in https domain, the tool don't verify the certificate:

```
conf := &tls.Config{
         InsecureSkipVerify: true,
    }
...
if os.Args[2] == "443" {
			s, err = tls.Dial("tcp", addr, conf)
		}
```

God job,
Regards.

### CODE REVIEW

**Comment by Leeon123** [comment]
Actually  , If you want to attack adomain with cdn or fast flux, you can just type the domain as host.

**Comment by Leeon123** [comment]
The tls.config i'll add.

**Comment by Leeon123** [comment]
I'm not really understand the improvement you said. Hope you can tell me more. And i'm not usually use this account so maybe i'll not reply you immediately.

**Comment by wagiro** [comment]
Hi @Leeon123 ,

Yes, with this improvement:

```
1- You can specify IP or IP and domain, for multiples domains in shared hosting.

fmt.Println("Usage: ", os.Args[0], "<ip> <port> <threads> <page> <get/post> <seconds> <header.txt/nil> <domain/nil>")
```

You can avoid the dns resolution every request.

Try to execute your program with a wireshark in the middle, and you can see the dns request resolution.

Regards.

**Comment by Leeon123** [comment]
Okk, I'll update this feature it but use my way, such as read file :)

**Pull request closed without merging**
